// AUTO-GENERATED by scripts/build-reference-layers.mjs — do not edit by hand.
// Pixel bands in 1080x1920 space: [top, bottom] per text line, artwork cut line.

export interface SceneLayout {
  header: [number, number];
  headlineLines: [number, number][];
  bodyLines: [number, number][];
  cutY: number;
}

export const PLATE_LAYOUT: Record<number, SceneLayout> = {
  "1": {
    "header": [
      101,
      138
    ],
    "headlineLines": [
      [
        211,
        305
      ],
      [
        310,
        387
      ],
      [
        452,
        524
      ],
      [
        527,
        599
      ]
    ],
    "bodyLines": [
      [
        642,
        687
      ]
    ],
    "cutY": 723
  },
  "2": {
    "header": [
      97,
      134
    ],
    "headlineLines": [
      [
        207,
        288
      ],
      [
        314,
        415
      ]
    ],
    "bodyLines": [
      [
        469,
        514
      ],
      [
        521,
        558
      ]
    ],
    "cutY": 666
  },
  "3": {
    "header": [
      99,
      136
    ],
    "headlineLines": [
      [
        212,
        291
      ],
      [
        319,
        397
      ]
    ],
    "bodyLines": [
      [
        463,
        508
      ],
      [
        516,
        560
      ]
    ],
    "cutY": 599
  },
  "4": {
    "header": [
      98,
      135
    ],
    "headlineLines": [
      [
        214,
        306
      ],
      [
        310,
        403
      ],
      [
        407,
        500
      ]
    ],
    "bodyLines": [
      [
        547,
        586
      ],
      [
        596,
        641
      ]
    ],
    "cutY": 670
  },
  "5": {
    "header": [
      96,
      133
    ],
    "headlineLines": [
      [
        212,
        296
      ],
      [
        314,
        399
      ]
    ],
    "bodyLines": [
      [
        467,
        507
      ],
      [
        520,
        566
      ]
    ],
    "cutY": 620
  },
  "6": {
    "header": [
      99,
      136
    ],
    "headlineLines": [
      [
        207,
        288
      ],
      [
        311,
        393
      ]
    ],
    "bodyLines": [
      [
        453,
        495
      ],
      [
        504,
        548
      ]
    ],
    "cutY": 650
  },
  "7": {
    "header": [
      99,
      136
    ],
    "headlineLines": [
      [
        208,
        303
      ],
      [
        307,
        402
      ],
      [
        408,
        486
      ]
    ],
    "bodyLines": [
      [
        548,
        592
      ],
      [
        595,
        639
      ]
    ],
    "cutY": 680
  },
  "8": {
    "header": [
      99,
      136
    ],
    "headlineLines": [
      [
        209,
        284
      ],
      [
        307,
        399
      ]
    ],
    "bodyLines": [
      [
        440,
        485
      ],
      [
        492,
        530
      ]
    ],
    "cutY": 587
  },
  "9": {
    "header": [
      98,
      135
    ],
    "headlineLines": [
      [
        209,
        300
      ],
      [
        307,
        379
      ]
    ],
    "bodyLines": [
      [
        447,
        485
      ],
      [
        499,
        537
      ]
    ],
    "cutY": 608
  },
  "10": {
    "header": [
      98,
      136
    ],
    "headlineLines": [
      [
        208,
        297
      ],
      [
        305,
        388
      ],
      [
        404,
        490
      ]
    ],
    "bodyLines": [
      [
        540,
        584
      ]
    ],
    "cutY": 623
  }
};
